/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Pikkart Srl (https://sketchfab.com/pikkartsrl)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/bungalow-moderno-di-design-con-interni-4ebc0b341f9e450aaed594974b0fe46c
Title: Bungalow Moderno di Design (con interni)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./bunglow/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.581, 2.285]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials['White_Wall_02-Freepoly.org_0']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Dark_iron_0} />
      </group>
      <group position={[-0.02, 1.581, -2.456]} rotation={[Math.PI, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials['White_Wall_02-Freepoly.org_0']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Dark_iron_0} />
      </group>
      <group position={[0.749, 0.095, 3.518]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.87, 1.265, 1]}>
        <group position={[-1.03, 1.628, -0.014]}>
          <mesh geometry={nodes.Object_76.geometry} material={materials.Roughness_Transparent_Plastic} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.light} />
        </group>
        <group position={[-0.247, 1.115, -0.083]} rotation={[Math.PI, 0.851, -Math.PI / 2]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.Object_123.geometry} material={materials.Anodized} />
          <mesh geometry={nodes.Object_124.geometry} material={materials.tap_hole} />
        </group>
        <group position={[-0.883, 1.604, -0.049]} rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Object_128.geometry} material={materials.grate} />
          <mesh geometry={nodes.Object_129.geometry} material={materials.brushed_metal} />
          <mesh geometry={nodes.Object_130.geometry} material={materials.plastic} />
        </group>
        <group position={[0.296, 0.888, 0.04]}>
          <mesh geometry={nodes.Object_136.geometry} material={materials.sink} />
          <mesh geometry={nodes.Object_137.geometry} material={materials.Anodized} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.sink_side_hole} />
        </group>
        <mesh geometry={nodes.Object_18.geometry} material={materials.cabinets_gray} position={[-0.075, 0.042, 0.172]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Bowls} position={[0.386, 1.636, -0.121]} scale={0.06} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.cabinets_gray} position={[-0.498, 0.469, -0.005]} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[-0.498, 0.63, 0.326]} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[-0.098, 0.395, 0.326]} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[0.736, 0.395, 0.326]} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[1.172, 0.395, 0.326]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Walnut_light_wood_fine_PBR_texture_seamless.001']} position={[-0.498, 0.779, 0.326]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Walnut_light_wood_fine_PBR_texture_seamless.001_0']} position={[0.101, 0.779, 0.326]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Walnut_light_wood_fine_PBR_texture_seamless.001']} position={[0.736, 0.779, 0.326]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Walnut_light_wood_fine_PBR_texture_seamless.001']} position={[1.172, 0.779, 0.326]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[1.172, 2.011, 0.055]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[0.736, 2.011, 0.055]} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[0.103, 2.091, 0.055]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[-0.507, 1.968, 0.055]} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.cabinets_gray} position={[-1.029, 0.471, 0.01]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Walnut_light_wood_fine_PBR_texture_seamless.001_0']} position={[-1.03, 0.779, 0.326]} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Walnut_light_wood_fine_PBR_texture_seamless} position={[-1.03, 0.552, 0.326]} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.cabinets_gray} position={[1.172, 0.471, -0.002]} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.cabinets_gray} position={[0.334, 0.495, 0.007]} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.cabinets_gray} position={[0.5, 0.482, 0.012]} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.cabinets_gray} position={[0.721, 1.609, -0.264]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.cabinets_gray} position={[1.157, 1.609, -0.264]} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.cabinets_gray} position={[0.285, 1.609, -0.264]} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.cabinets_gray} position={[-0.516, 1.609, -0.264]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Anodized} position={[-0.317, 0.965, -0.021]} rotation={[Math.PI / 2, 0, -2.29]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Anodized} position={[-0.294, 1.033, -0.041]} rotation={[Math.PI, 0.851, -Math.PI / 2]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.brushed_metal} position={[-1.019, 0.893, 0.032]} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.brushed_metal_hood} position={[-1.03, 1.628, -0.014]} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.plastic} position={[-1.03, 1.628, -0.014]} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.material} position={[0.58, 0.888, -0.087]} rotation={[0, -1.058, 0]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.material} position={[0.258, 1.626, -0.142]} rotation={[0, 0.472, 0]} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.material} position={[0.297, 1.626, -0.021]} rotation={[0, -0.676, 0]} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.material} position={[0.213, 1.626, -0.045]} rotation={[-Math.PI, 0.279, -Math.PI]} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Wood} position={[0.762, 0.888, 0.062]} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Anodized} position={[-0.498, 0.792, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Anodized} position={[0.736, 0.792, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Anodized} position={[1.172, 0.792, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Anodized} position={[0.736, 0.233, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.Anodized} position={[0.101, 0.779, 0.326]} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.Anodized} position={[1.027, 0.603, 0.346]} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.Anodized} position={[-0.498, 0.658, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.Anodized} position={[1.027, 1.738, 0.075]} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.Anodized} position={[0.851, 1.738, 0.075]} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.Anodized} position={[0.103, 1.903, 0.074]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.Anodized} position={[-0.368, 1.738, 0.075]} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.Anodized} position={[-1.03, 0.792, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.Anodized} position={[-1.03, 0.664, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.Anodized} position={[-1.03, 0.348, 0.346]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.brushed_metal_hood} position={[-1.03, 1.628, -0.014]} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.Knife} position={[0.803, 0.899, 0.121]} rotation={[-1.521, -0.008, -0.349]} scale={1.344} />
        <mesh geometry={nodes.Object_126.geometry} material={materials.cooking_mat} position={[-1.019, 0.893, 0.032]} />
        <mesh geometry={nodes.Object_132.geometry} material={materials.Cup_0} position={[-0.106, 1.643, -0.113]} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.Anodized} position={[-0.247, 0.897, -0.083]} rotation={[Math.PI, 0.851, -Math.PI]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.sink_0} position={[0.1, 0.744, 0.04]} />
        <mesh geometry={nodes.Object_142.geometry} material={materials.Artificial_Marble_1} position={[0.336, 0.869, 0.036]} />
        <mesh geometry={nodes.Object_144.geometry} material={materials.Artificial_Marble_1} position={[0.336, 0.869, 0.036]} />
      </group>
      <group position={[-0.14, 0.095, 3.464]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.033}>
        <group position={[0.246, 0.705, 0.1]} rotation={[0, -0.86, 0]}>
          <mesh geometry={nodes.Object_148.geometry} material={materials.Plastic_white_smooth} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.Plastic_white_smooth} position={[-0.293, 0, 0.355]} />
        </group>
        <group position={[0, 0.228, -0.066]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_152.geometry} material={materials.Plastic_white_smooth} />
          <mesh geometry={nodes.Object_153.geometry} material={materials.Glas} />
        </group>
        <group position={[0, 0.325, -0.066]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_155.geometry} material={materials.Plastic_white_smooth} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.Glas} />
        </group>
        <group position={[0, 0.435, -0.066]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_158.geometry} material={materials.Plastic_white_smooth} />
          <mesh geometry={nodes.Object_159.geometry} material={materials.Glas} />
        </group>
        <group position={[0.296, 0.211, 0.295]} rotation={[0, -0.86, 0]}>
          <mesh geometry={nodes.Object_163.geometry} material={materials.Plastic_white_smooth} />
          <mesh geometry={nodes.Object_164.geometry} material={materials.Metal_white_smooth} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.Plexiglas} position={[-0.173, 0.05, 0.236]} rotation={[0, 0.87, 0]} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.Plexiglas} position={[-0.202, 0.455, 0.213]} rotation={[0, 0.87, 0]} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.Plexiglas} position={[-0.173, 0.369, 0.236]} rotation={[0, 0.87, 0]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.Plexiglas} position={[-0.173, 0.244, 0.236]} rotation={[0, 0.87, 0]} />
        </group>
        <mesh geometry={nodes.Object_146.geometry} material={materials.Plastic_white_smooth} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.Plastic_white_smooth} position={[0.236, 0.549, 0]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_174.geometry} material={materials.Plexiglas} position={[0, 0.069, 0]} />
        <mesh geometry={nodes.Object_176.geometry} material={materials.Emission} position={[0.001, 0.606, -0.078]} rotation={[2.267, 0, 0]} />
      </group>
      <group position={[2.029, 0.1, 1.314]} rotation={[0, Math.PI / 2, 0]} scale={[1.713, 1.378, 1.378]}>
        <group position={[-1.05, 0.02, -0.037]}>
          <mesh geometry={nodes.Object_179.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.Glass} />
        </group>
        <group position={[-1.018, 0.118, 0.008]}>
          <mesh geometry={nodes.Object_186.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.Glass} />
        </group>
        <group position={[1.018, 0.118, 0.008]}>
          <mesh geometry={nodes.Object_189.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.Glass} />
        </group>
        <mesh geometry={nodes.Object_182.geometry} material={materials.Dark_iron_1} position={[0, 0, 0.002]} />
        <mesh geometry={nodes.Object_184.geometry} material={materials.material_37} position={[1.05, 0.02, -0.072]} />
      </group>
      <group position={[2.029, 0.1, -2.286]} rotation={[0, Math.PI / 2, 0]} scale={1.365}>
        <group position={[-0.6, 0.02, -0.037]}>
          <mesh geometry={nodes.Object_193.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_194.geometry} material={materials.Glass} />
        </group>
        <group position={[-0.571, 0.118, 0.008]}>
          <mesh geometry={nodes.Object_200.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_201.geometry} material={materials.Glass} />
        </group>
        <mesh geometry={nodes.Object_196.geometry} material={materials.Dark_iron_1} position={[0, 0, 0.002]} />
        <mesh geometry={nodes.Object_198.geometry} material={materials['PVC.001']} position={[0.6, 0.02, -0.072]} />
      </group>
      <group position={[-0.851, 0.1, -4.014]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.365}>
        <group position={[-0.6, 0.02, -0.037]}>
          <mesh geometry={nodes.Object_204.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_205.geometry} material={materials.Glass} />
        </group>
        <group position={[-0.571, 0.118, 0.008]}>
          <mesh geometry={nodes.Object_211.geometry} material={materials.Dark_iron_1} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.Glass} />
        </group>
        <mesh geometry={nodes.Object_207.geometry} material={materials.Dark_iron_1} position={[0, 0, 0.002]} />
        <mesh geometry={nodes.Object_209.geometry} material={materials['PVC.001']} position={[0.6, 0.02, -0.072]} />
      </group>
      <group position={[0.84, 0.095, 0.976]} rotation={[0, -Math.PI / 2, 0]} scale={1.21}>
        <group position={[0.001, 0, 0.294]}>
          <mesh geometry={nodes.Object_215.geometry} material={materials.Leather} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.Metal} />
        </group>
        <group position={[-0.504, 0, 0.001]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_218.geometry} material={materials.Leather} />
          <mesh geometry={nodes.Object_219.geometry} material={materials.Metal} />
        </group>
        <group position={[-0.001, 0, -0.302]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Object_221.geometry} material={materials.Leather} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.Metal} />
        </group>
        <group position={[0.504, 0, -0.001]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes.Object_224.geometry} material={materials.Leather} />
          <mesh geometry={nodes.Object_225.geometry} material={materials.Metal} />
        </group>
        <mesh geometry={nodes.Object_227.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_228.geometry} material={materials['Glass.002']} />
      </group>
      <group position={[0.946, 0.095, -0.683]} scale={1.008}>
        <group position={[0, 0.087, -0.005]}>
          <mesh geometry={nodes.Object_237.geometry} material={materials.wood_Oak_Matt_Antracite_Gray} />
          <mesh geometry={nodes.Object_239.geometry} material={materials.ceramic} position={[-0.9, 0.01, -0.184]} />
          <mesh geometry={nodes.Object_241.geometry} material={materials.ceramic_0} position={[-0.6, 0.086, 0.176]} />
          <mesh geometry={nodes.Object_243.geometry} material={materials.ceramic_0} position={[-0.3, 0.01, -0.184]} />
          <mesh geometry={nodes.Object_245.geometry} material={materials.ceramic_0} position={[0.3, 0.01, -0.184]} />
          <mesh geometry={nodes.Object_247.geometry} material={materials.wood_Oak_Matt_Antracite_Gray} position={[-0.762, -0.032, -0.139]} rotation={[0.155, 0, -0.235]} scale={[0.014, 0.037, 0.014]} />
        </group>
        <group position={[0, 0.363, -0.024]}>
          <mesh geometry={nodes.Object_250.geometry} material={materials.frame} position={[-0.036, 1.327, -0.112]} scale={1.003} />
        </group>
      </group>
      <group position={[0.945, 0.095, -2.936]} scale={[0.754, 0.913, 0.913]}>
        <group position={[0, 0.281, 0.09]}>
          <mesh geometry={nodes.Object_253.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Object_254.geometry} material={materials['Material.005']} />
        </group>
        <mesh geometry={nodes.Object_256.geometry} material={materials.Leather_02} position={[0, 0.269, 0.078]} />
        <mesh geometry={nodes.Object_258.geometry} material={materials.stofa_saltea} position={[0, 0.269, 0.078]} />
        <mesh geometry={nodes.Object_260.geometry} material={materials.Leather_02} position={[0, 0.477, -1.043]} />
        <mesh geometry={nodes.Object_262.geometry} material={materials['Material.003']} position={[0.88, 0, 1.023]} scale={[0.03, 0.025, 0.03]} />
        <mesh geometry={nodes.Object_264.geometry} material={materials['Material.003']} position={[-0.915, 0, 1.023]} scale={[0.03, 0.025, 0.03]} />
        <mesh geometry={nodes.Object_266.geometry} material={materials['Material.003']} position={[0.91, 0, -1.03]} scale={[0.03, 0.025, 0.03]} />
        <mesh geometry={nodes.Object_268.geometry} material={materials['Material.003']} position={[-0.945, 0, -1.03]} scale={[0.03, 0.025, 0.03]} />
        <mesh geometry={nodes.Object_270.geometry} material={materials.stofa_perna} position={[0.449, 0.6, -0.707]} />
        <mesh geometry={nodes.Object_272.geometry} material={materials.stofa_perna} position={[-0.38, 0.6, -0.707]} />
      </group>
      <group position={[-0.424, 2.154, 2.305]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_274.geometry} material={materials.PORTA_TINTA} />
        <mesh geometry={nodes.Object_275.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_276.geometry} material={materials.Carvalho} />
        <mesh geometry={nodes.Object_277.geometry} material={materials.quadro_figura} />
      </group>
      <group position={[-1.225, 0.095, 1.17]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.124}>
        <group position={[-0.059, 0.004, -0.006]}>
          <group position={[0.494, 0.001, 0.084]}>
            <mesh geometry={nodes.Object_283.geometry} material={materials.wood} />
            <mesh geometry={nodes.Object_284.geometry} material={materials.stainless} />
            <mesh geometry={nodes.Object_285.geometry} material={materials.black} />
          </group>
          <mesh geometry={nodes.Object_280.geometry} material={materials.wood} />
          <mesh geometry={nodes.Object_281.geometry} material={materials.stainless} />
        </group>
      </group>
      <group position={[0.053, 0.095, -1.561]} rotation={[0, -Math.PI / 2, 0]} scale={1.124}>
        <group position={[-0.059, 0.004, -0.006]}>
          <group position={[0.494, 0.001, 0.084]}>
            <mesh geometry={nodes.Object_291.geometry} material={materials.wood} />
            <mesh geometry={nodes.Object_292.geometry} material={materials.stainless} />
            <mesh geometry={nodes.Object_293.geometry} material={materials.black} />
          </group>
          <mesh geometry={nodes.Object_288.geometry} material={materials.wood} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.stainless} />
        </group>
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Wooden_plank} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Dark_iron} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.concrete} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Marble_4} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Bricks} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['White_Wall_02-Freepoly.org']} />
      <mesh geometry={nodes.Object_230.geometry} material={materials['Material.002']} position={[0.981, 3.031, 0.313]} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_232.geometry} material={materials['Material.002']} position={[-0.489, 3.031, -0.435]} rotation={[Math.PI, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_234.geometry} material={materials['Material.002']} position={[0.981, 3.031, -2.564]} rotation={[Math.PI, Math.PI / 2, 0]} />
    </group>
  )
}
useGLTF.preload('/scene.gltf')
